### ISSUE TITLE
Event Implementation Progress Tracker

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeForge#274]
**Event Progress Trackers:** SpongeForge | [SpongeCommon](https://github.com/SpongePowered/SpongeCommon/issues/41) | [SpongeVanilla](https://github.com/SpongePowered/SpongeVanilla/issues/168)
## Progress tracker for events to be mixed-in with Forge events

**Please keep this updated Sponge devs!**

`achievement.GrantAchievementEvent.TargetPlayer`
- [ ] Mixed into `net.minecraftforge.event.entity.player.AchievementEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`action.LightningEvent.Strike`
- [ ] Mixed into `net.minecraftforge.event.entity.EntityStruckByLightningEvent.EntityStruckByLightningEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`action.SleepingEvent.Finish`
- [ ] Mixed into `net.minecraftforge.event.entity.player.PlayerWakeUpEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`action.SleepingEvent.Pre`
- [x] Mixed into `net.minecraftforge.event.entity.player.PlayerSleepInBedEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`block.ChangeBlockEvent.Break`
- [x] Mixed into `net.minecraftforge.event.world.BlockEvent.BreakEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`block.ChangeBlockEvent.Fluid`
- [ ] Mixed into `net.minecraftforge.fluids.FluidEvent.FluidSpilledEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`block.ChangeBlockEvent.Place`
- [x] Mixed into `net.minecraftforge.event.world.BlockEvent.PlaceEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`block.InteractBlockEvent`
- [x] Mixed into `net.minecraftforge.event.entity.player.PlayerInteractEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`block.NotifyNeighborBlockEvent`
- [x] Mixed into `net.minecraftforge.event.world.BlockEvent.NeighborNotifyEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`block.tileentity.BrewingEvent.Finish`
- [ ] Mixed into `net.minecraftforge.event.brewing.PotionBrewEvent.Post`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`block.tileentity.BrewingEvent.Start`
- [ ] Mixed into `net.minecraftforge.event.brewing.PotionBrewEvent.Pre`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`command.SendCommandEvent`
- [ ] Mixed into `net.minecraftforge.event.CommandEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`entity.ConstructEntityEvent.Post`
- [x] Mixed into `net.minecraftforge.event.entity.EntityEvent.EntityConstructing`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`entity.DestructEntityEvent.Death`
- [x] Mixed into `net.minecraftforge.event.entity.living.LivingDeathEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`entity.ExpireEntityEvent.TargetItem`
- [x] Mixed into `net.minecraftforge.event.entity.item.ItemExpireEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`entity.InteractEntityEvent.Secondary`
- [x] Mixed into `net.minecraftforge.event.entity.player.EntityInteractEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`entity.RideEntityEvent.Dismount`
- [ ] Mixed into `net.minecraftforge.event.entity.EntityMountEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`entity.RideEntityEvent.Mount`
- [ ] Mixed into `net.minecraftforge.event.entity.EntityMountEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`entity.SpawnEntityEvent`
- [x] Mixed into `net.minecraftforge.event.entity.EntityJoinWorldEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`entity.SpawnEntityEvent.Spawner`
- [ ] Mixed into `net.minecraftforge.event.entity.living.LivingSpawnEvent.SpecialSpawn`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`entity.living.humanoid.player.RespawnPlayerEvent`
- [x] Mixed into `net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerRespawnEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameAboutToStartServerEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLServerAboutToStartEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameConstructionEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLConstructionEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameInitializationEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLInitializationEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameLoadCompleteEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLLoadCompleteEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GamePostInitializationEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLPostInitializationEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GamePreInitializationEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLPreInitializationEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameStartedServerEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLServerStartedEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameStartingServerEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLServerStartingEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameStoppedServerEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLServerStoppedEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`game.state.GameStoppingServerEvent`
- [x] Mixed into `net.minecraftforge.fml.common.event.FMLServerStoppingEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`item.inventory.ChangeInventoryEvent.Pickup`
- [ ] Mixed into `net.minecraftforge.fml.common.gameevent.PlayerEvent.ItemPickupEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`item.inventory.DropItemEvent.Dispense`
- [x] Mixed into `net.minecraftforge.event.entity.item.ItemTossEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`item.inventory.InteractInventoryEvent.Open`
- [ ] Mixed into `net.minecraftforge.event.entity.player.PlayerOpenContainerEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`item.inventory.UseItemStackEvent.Finish`
- [x] Mixed into `net.minecraftforge.event.entity.player.PlayerUseItemEvent.Finish`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`item.inventory.UseItemStackEvent.Start`
- [x] Mixed into `net.minecraftforge.event.entity.player.PlayerUseItemEvent.Start`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`item.inventory.UseItemStackEvent.Stop`
- [x] Mixed into `net.minecraftforge.event.entity.player.PlayerUseItemEvent.Stop`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`item.inventory.UseItemStackEvent.Tick`
- [x] Mixed into `net.minecraftforge.event.entity.player.PlayerUseItemEvent.Tick`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`message.MessageChannelEvent.Chat`
- [x] Mixed into `net.minecraftforge.event.ServerChatEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`network.ClientConnectionEvent.Disconnect`
- [x] Mixed into `net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedOutEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`network.ClientConnectionEvent.Join`
- [x] Mixed into `net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`world.ExplosionEvent.Detonate`
- [x] Mixed into `net.minecraftforge.event.world.ExplosionEvent.Detonate`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`world.ExplosionEvent.Pre`
- [x] Mixed into `net.minecraftforge.event.world.ExplosionEvent.Start`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`world.LoadWorldEvent`
- [x] Mixed into `net.minecraftforge.event.world.WorldEvent.Load`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`world.SaveWorldEvent`
- [ ] Mixed into `net.minecraftforge.event.world.WorldEvent.Save`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`world.UnloadWorldEvent`
- [x] Mixed into `net.minecraftforge.event.world.WorldEvent.Unload`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`world.chunk.ForcedChunkEvent`
- [ ] Mixed into `net.minecraftforge.common.ForgeChunkManager.ForceChunkEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`world.chunk.LoadChunkEvent`
- [x] Mixed into `net.minecraftforge.event.world.ChunkEvent.Load`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

`world.chunk.PopulateChunkEvent.Post`
- [ ] Mixed into `net.minecraftforge.event.terraingen.PopulateChunkEvent.Post`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`world.chunk.PopulateChunkEvent.Pre`
- [ ] Mixed into `net.minecraftforge.event.terraingen.PopulateChunkEvent.Pre`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`world.chunk.UnforcedChunkEvent`
- [ ] Mixed into `net.minecraftforge.common.ForgeChunkManager.UnforceChunkEvent`
- [ ] Interface implemented (all methods)
- [ ] In `bleeding` branch

`world.chunk.UnloadChunkEvent`
- [x] Mixed into `net.minecraftforge.event.world.ChunkEvent.Unload`
- [x] Interface implemented (all methods)
- [x] In `bleeding` branch

**Comment by TheAwesomeGem** [comment]
How about inventory.ContainerModifyEvent or ContainerItemMoveEvent to keep track of an item being moved inside a container or from one container to another container and to be able to cancel the movement? Much like InventoryMoveItemEvent on Bukkit.

**Comment by simon816** [comment]
@TheAwesomeGem This is not a place to suggest events; this is just a tracker. Please use [SpongeAPI issues](https://github.com/SpongePowered/SpongeAPI/issues) for API suggestions.

**Comment by kenzierocks** [comment]
Might be a good idea to lock this.

**Comment by ArcasCZ** [comment]
What about GrantAchievementEvent?

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/41#issuecomment-517764256
